name: Deploy to GitHub Pages

on:
  push:
    branches: ["wasm"]
  paths-ignore:
    - "*.md"

permissions:
  contents: read
  pages: write # Required to deploy to Pages
  id-token: write # Required for authentication

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "yarn"
          cache-dependency-path: "website/yarn.lock"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Cache rust deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache wasm package
        id: cache-wasm
        uses: actions/cache@v4
        with:
          path: ./pkg
          key: ${{ runner.os }}-pkg-${{ hashFiles('src/**') }}

      - name: Install wasm-pack
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        run: cargo install wasm-pack

      - name: Add rust-std
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build wasm pkg
        if: steps.cache-wasm.outputs.cache-hit != 'true'
        run: RUSTUP_TOOLCHAIN=nightly RUSTFLAGS="-C target-feature=+atomics,+bulk-memory -Clink-arg=--shared-memory -Clink-arg=--max-memory=1073741824 -Clink-arg=--import-memory -Clink-arg=--export=__wasm_init_tls -Clink-arg=--export=__tls_size -Clink-arg=--export=__tls_align -Clink-arg=--export=__tls_base" wasm-pack build --target web

      - name: Install dependencies
        working-directory: ./website
        run: yarn install --immutable

      - name: Build
        run: |
          cp -r pkg/ website/
          cd website
          yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./website/dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
